# Generated by Django 5.2.3 on 2025-07-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streams", "0003_alter_live_stream_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streamkey",
            name="platform",
            field=models.CharField(
                choices=[
                    ("YouTube", "YouTube"),
                    ("Twitch", "Twitch"),
                    ("Facebook", "Facebook"),
                    ("Instagram", "Instagram"),
                    ("TikTok", "TikTok"),
                    ("Autre", "Autre"),
                ],
                default="YouTube",
                max_length=50,
                verbose_name="Plateforme",
            ),
        ),
    ]
